# stage 4(copy) >> Challenge2
## 신발 사이즈 분석

In [1]:
import pandas as pd

df = pd.read_csv('data/korean_players.csv')
df.head()

이름  적합사이즈  나이  출장수    키  몸무게
0  조현우    275  27   12  189   75
1  김영권    285  29   69  186   81
2  김민재    290  22   19  190   88
3  이청용    265  30   89  180   70
4  손흥민    260  26   79  183   77

In [2]:
df.describe()

적합사이즈         나이        출장수           키        몸무게
count   10.000000  10.000000  10.000000   10.000000  10.000000
mean   273.500000  24.700000  34.600000  181.500000  72.800000
std     10.013879   3.802046  33.383962    6.398785   7.828722
min    260.000000  18.000000   0.000000  170.000000  63.000000
25%    266.250000  22.000000  10.500000  180.000000  68.500000
50%    275.000000  26.000000  22.000000  181.500000  71.500000
75%    278.750000  26.750000  62.500000  185.500000  76.500000
max    290.000000  30.000000  89.000000  190.000000  88.000000

In [15]:
x_train = df[['나이','출장수','키','몸무게']]
y_train = df['적합사이즈']

In [16]:
from sklearn.linear_model import LinearRegression

lr = LinearRegression().fit(x_train, y_train)

print('train set accuracy: ', lr.score(x_train,y_train))

train set accuracy:  0.6550739388896691


**보완할 점**
1. 다량의 데이터 확보
2. 사전 탐색, 분석 작업 필요
3. validation set, test set 을 만들어 모델 성능 평가+ 평가기준에 관한 고민
4. 더많은 테스트 데이터 확보

## 모델 적용해보기

In [5]:
df_test = pd.read_csv('data/test_players.csv')
df_test

이름  나이  출장수    키  몸무게
0  황인범  22   14  177   67
1  김신욱  31   51  196   93

In [6]:
x_test = df_test[['나이','출장수','키','몸무게']]

prediction = lr.predict(x_test)
prediction
# 데이터의 양과 질을 높이면 더 정확한 예측이 가능

array([270.2212304 , 295.31336894])

In [7]:
lr.predict([[15,0,180,80],[25,5,160,60]])

array([280.27344808, 272.20473106])

# challenge2

In [8]:
comparison = pd.DataFrame(y_train)
comparison

적합사이즈
0    275
1    285
2    290
3    265
4    260
5    275
6    280
7    270
8    260
9    275

In [11]:
y_test = lr.predict(x_train) #x_train을 가지고 예측해줘
y_test

array([281.8296389 , 277.8828813 , 289.4745801 , 263.17652819,
       268.55981641, 270.05240973, 273.91711351, 265.90455468,
       267.47623672, 276.72624047])

In [12]:
comparison['나의 예측'] = y_test
comparison

적합사이즈       나의 예측
0    275  281.829639
1    285  277.882881
2    290  289.474580
3    265  263.176528
4    260  268.559816
5    275  270.052410
6    280  273.917114
7    270  265.904555
8    260  267.476237
9    275  276.726240